# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Ubuntu

on:
- push

env:
  SSH_ACTIONS: false
  moon: true

jobs:
  install_zerotier:
    name: Install zerotier by bash script on the offical page.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        #- ubuntu-18.04
        - ubuntu-20.04
    steps:

    - name: Checkout source codes
      uses: actions/checkout@v2

    - name: Install zerotier one
      run: curl -s https://install.zerotier.com | sudo bash

    - name: Update system
      run: |
        sudo apt-get -E update
        sudo apt-get -E full-upgrade

    - name: join network Id
      run: sudo zerotier-cli join ${{ secrets.NETWORK_ID }}

    - name: orbit moon
      if: env.MOON_ID == 'true'
      run: sudo zerotier-cli orbit ${{ secrets.MOON_ID }} ${{ secrets.MOON_ID }}

    - name: check /root/.ssh directory
      run: |
        if [ ! /root  ]; then sudo mkdir /root; fi
        if [ ! /root/.ssh ]; then sudo mkdir /root/.ssh; fi

    - name: sshd public add and fix permission
      run: |
        echo ${{ secrets.SSH_PUBLIC_KEY }} | sudo tee -a /root/.ssh/authorized_keys
        sudo chmod 0600 /root/.ssh/authorized_keys

    - name: run machine by tail
      if: env.SSH_ACTIONS == 'false'
      run: tail -f /dev/null

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: env.SSH_ACTIONS == 'true'
